# http://www.appveyor.com/docs/appveyor-yml

version: "{build}"

environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: stable

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test
